CREATE TABLE movies (
                        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title       VARCHAR(150) NOT NULL,
                        description TEXT         NOT NULL,
                        cover_path  VARCHAR(255),
                        score       NUMERIC(3,1) NOT NULL CHECK (score BETWEEN 0 AND 10),
                        status      VARCHAR(20)  NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED')),
                        created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
                        updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);