CREATE TABLE rentals (
                         id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         movie_id       BIGINT       NOT NULL,
                         movie_title    VARCHAR(150) NOT NULL,
                         customer_name  VARCHAR(100) NOT NULL,
                         customer_email VARCHAR(150) NOT NULL,
                         rented_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
                         due_date       TIMESTAMPTZ  NOT NULL,
                         returned_at    TIMESTAMPTZ,
                         status         VARCHAR(20)  NOT NULL CHECK (status IN ('ACTIVE', 'RETURNED'))
);